name: Build WAR File

on:
  push:
    branches:
      - main   # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest  # This specifies that we are using Windows for this job.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\20.0.2-9\x64
          JAVA_HOME_20_X64: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\20.0.2-9\x64

